name: emo
channels:
  - pytorch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - alsa-lib=1.2.8=h166bdaf_0
  - aom=3.5.0=h27087fc_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - attr=2.5.1=h166bdaf_1
  - blas=1.0=mkl
  - blosc=1.21.3=h6a678d5_0
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - brotlipy=0.7.0=py39h27cfd23_1003
  - brunsli=0.1=h2531618_0
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.18.1=h7f8727e_0
  - ca-certificates=2024.3.11=h06a4308_0
  - cairo=1.16.0=ha61ee94_1014
  - certifi=2024.2.2=py39h06a4308_0
  - cffi=1.15.1=py39h5eee18b_3
  - cfitsio=3.470=h5893167_7
  - charls=2.2.0=h2531618_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cloudpickle=2.0.0=pyhd3eb1b0_0
  - cryptography=39.0.1=py39h9ce1e76_0
  - cudatoolkit=11.3.1=h9edb442_11
  - cycler=0.11.0=pyhd3eb1b0_0
  - cytoolz=0.12.0=py39h5eee18b_0
  - dask-core=2022.7.0=py39h06a4308_0
  - dbus=1.13.18=hb2f20db_0
  - expat=2.5.0=h27087fc_0
  - ffmpeg=5.1.2=gpl_h8dda1f0_106
  - fftw=3.3.10=nompi_hf0379b8_106
  - flit-core=3.6.0=pyhd3eb1b0_0
  - font-ttf-dejavu-sans-mono=2.37=0
  - font-ttf-inconsolata=2.000=0
  - font-ttf-source-code-pro=2.030=0
  - font-ttf-ubuntu=0.83=0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - freeglut=3.2.2=h9c3ff4c_1
  - freetype=2.12.1=h4a9f257_0
  - fsspec=2022.11.0=py39h06a4308_0
  - geos=3.8.0=he6710b0_0
  - gettext=0.21.1=h27087fc_0
  - giflib=5.2.1=h5eee18b_3
  - glib=2.74.1=h6239696_0
  - glib-tools=2.74.1=h6239696_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.7.8=hf3e180e_0
  - graphite2=1.3.14=h295c915_1
  - gst-plugins-base=1.21.3=h4243ec0_1
  - gstreamer=1.21.3=h25f0c4b_1
  - harfbuzz=6.0.0=h8e241bc_0
  - hdf5=1.12.2=nompi_h2386368_100
  - icu=70.1=h27087fc_0
  - idna=3.4=py39h06a4308_0
  - imagecodecs=2021.8.26=py39hfcb8610_2
  - imageio=2.26.0=py39h06a4308_0
  - imgaug=0.4.0=pyhd3eb1b0_0
  - importlib_resources=5.2.0=pyhd3eb1b0_1
  - intel-openmp=2021.4.0=h06a4308_3561
  - jack=1.9.22=h11f4161_0
  - jasper=2.0.33=h0ff4b12_1
  - joblib=1.4.0=py39h06a4308_0
  - jpeg=9e=h5eee18b_1
  - jxrlib=1.1=h7b6447c_2
  - kiwisolver=1.4.4=py39h6a678d5_0
  - krb5=1.19.4=h568e23c_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libaec=1.0.4=he6710b0_1
  - libblas=3.9.0=12_linux64_mkl
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libcap=2.66=ha37c62d_0
  - libcblas=3.9.0=12_linux64_mkl
  - libclang=15.0.7=default_had23c3d_1
  - libclang13=15.0.7=default_h3e3d535_1
  - libcups=2.3.3=h3e49a29_2
  - libcurl=7.87.0=h91b91d3_0
  - libdb=6.2.32=h6a678d5_1
  - libdeflate=1.17=h5eee18b_0
  - libdrm=2.4.114=h166bdaf_0
  - libedit=3.1.20221030=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.10=h9b69904_4
  - libffi=3.4.2=h6a678d5_6
  - libflac=1.4.2=h27087fc_0
  - libgcc-ng=12.2.0=h65d4601_19
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.74.1=h7a41b64_0
  - libglu=9.0.0=hf484d3e_1
  - libiconv=1.17=h166bdaf_0
  - libidn2=2.3.2=h7f8727e_0
  - liblapack=3.9.0=12_linux64_mkl
  - liblapacke=3.9.0=12_linux64_mkl
  - libllvm15=15.0.7=hadd5161_0
  - libnghttp2=1.46.0=hce63b2e_0
  - libogg=1.3.5=h27cfd23_1
  - libopencv=4.7.0=py39hb375605_0
  - libopus=1.3.1=h7b6447c_0
  - libpciaccess=0.17=h166bdaf_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=14.5=h72a31a5_3
  - libprotobuf=3.21.12=h3eb15da_0
  - libsndfile=1.1.0=hcb278e6_1
  - libsqlite=3.40.0=h753d276_0
  - libssh2=1.10.0=h8f2d780_0
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libtasn1=4.19.0=h166bdaf_0
  - libtiff=4.5.0=h6a678d5_2
  - libtool=2.4.2=0
  - libudev1=253=h0b41bf4_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=2.32.1=h7f98852_1000
  - libuv=1.44.2=h5eee18b_0
  - libva=2.17.0=h0b41bf4_0
  - libvorbis=1.3.7=h7b6447c_0
  - libvpx=1.11.0=h295c915_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - libxcb=1.13=h7f98852_1004
  - libxkbcommon=1.5.0=h79f4944_0
  - libxml2=2.10.3=h7463322_0
  - libzlib=1.2.13=h166bdaf_4
  - libzopfli=1.0.3=he6710b0_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - locket=1.0.0=py39h06a4308_0
  - lz4-c=1.9.4=h6a678d5_0
  - matplotlib-base=3.7.0=py39h417a72b_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_fft=1.3.1=py39hd3c417c_0
  - mkl_random=1.2.2=py39h51133e4_0
  - mpg123=1.31.2=hcb278e6_0
  - munkres=1.1.4=py_0
  - mysql-common=8.0.32=h14678bc_0
  - mysql-libs=8.0.32=h54cf53e_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.8.1=hc379101_1
  - networkx=2.8.4=py39h06a4308_0
  - nspr=4.35=h27087fc_0
  - nss=3.88=he45b914_0
  - numpy=1.23.5=py39h14f4228_0
  - numpy-base=1.23.5=py39h31eccc5_0
  - opencv=4.7.0=py39hf3d152e_0
  - openh264=2.3.1=hcb278e6_2
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=1.1.1w=h7f8727e_0
  - p11-kit=0.24.1=hc5aa10d_0
  - partd=1.2.0=pyhd3eb1b0_1
  - pcre2=10.37=he7ceb23_1
  - pillow=9.3.0=py39hace64e9_1
  - pip=22.3.1=py39h06a4308_0
  - pixman=0.40.0=h7f8727e_1
  - pooch=1.4.0=pyhd3eb1b0_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pulseaudio=14.0=h0d2025b_11
  - py-opencv=4.7.0=py39hcca971b_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.0.0=py39h06a4308_0
  - pyparsing=3.0.9=py39h06a4308_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.16=h7a1cb2a_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.9=2_cp39
  - pytorch=1.10.1=py3.9_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - pywavelets=1.4.1=py39h5eee18b_0
  - pyyaml=6.0=py39h5eee18b_1
  - qt-main=5.15.6=hd477bba_1
  - readline=8.2=h5eee18b_0
  - requests=2.28.1=py39h06a4308_0
  - scikit-image=0.19.3=py39h6a678d5_1
  - scikit-learn=1.4.2=py39h1128e8f_1
  - setuptools=65.6.3=py39h06a4308_0
  - shapely=1.8.4=py39h81ba7c5_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.9=h295c915_0
  - sqlite=3.40.1=h5082296_0
  - svt-av1=1.4.1=hcb278e6_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tifffile=2021.7.2=pyhd3eb1b0_2
  - tk=8.6.12=h1ccaba5_0
  - toolz=0.12.0=py39h06a4308_0
  - torchaudio=0.10.1=py39_cu113
  - torchvision=0.11.2=py39_cu113
  - typing_extensions=4.4.0=py39h06a4308_0
  - tzdata=2022g=h04d1e81_0
  - urllib3=1.26.14=py39h06a4308_0
  - wheel=0.38.4=py39h06a4308_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xcb-util=0.4.0=h166bdaf_0
  - xcb-util-image=0.4.0=h166bdaf_0
  - xcb-util-keysyms=0.4.0=h166bdaf_0
  - xcb-util-renderutil=0.3.9=h166bdaf_0
  - xcb-util-wm=0.4.1=h166bdaf_0
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-inputproto=2.3.2=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.8.4=h0b41bf4_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h7f98852_0
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h27cfd23_1007
  - xz=5.2.10=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zfp=0.5.5=h295c915_6
  - zlib=1.2.13=h166bdaf_4
  - zstd=1.5.2=ha4553b6_0
  - pip:
    - addict==2.4.0
    - click==8.1.3
    - colorama==0.4.6
    - contourpy==1.0.7
    - fonttools==4.39.0
    - importlib-metadata==6.0.0
    - importlib-resources==5.12.0
    - markdown==3.4.1
    - markdown-it-py==2.2.0
    - matplotlib==3.7.1
    - mdurl==0.1.2
    - mmcv==1.3.10
    - mmcv-full==1.4.0
    - model-index==0.1.11
    - opencv-python==4.7.0.72
    - openmim==0.3.6
    - ordered-set==4.1.0
    - packaging==23.0
    - pandas==1.5.3
    - pycocotools==2.0.6
    - pygments==2.14.0
    - pytz==2022.7.1
    - rich==13.3.2
    - scipy==1.10.1
    - tabulate==0.9.0
    - terminaltables==3.1.10
    - tqdm==4.67.1
    - yapf==0.32.0
    - zipp==3.15.0
prefix: /public/home/lsy/anaconda3/envs/emo
